name: flutter_gzxjyh
description: 国祯巡检养护

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^2.0.17
  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.0
  barcode_scan: ^0.0.8
  # https://github.com/tekartik/synchronized.dart
  synchronized: ^2.0.2+1
  event_bus: ^1.0.3
  url_launcher: ^5.0.1
  flutter_picker: ^1.0.7
  # 高德地图  https://github.com/OpenFlutter/amap_base_flutter
  amap_base: ^0.2.11+3
  # 图片选择  https://github.com/Sh1d0w/multi_image_picker
  multi_image_picker: ^3.0.14
  # 录音 https://pub.flutter-io.cn/packages/flutter_sound
  flutter_sound: ^1.3.3
  path_provider: ^0.5.0+1
  # 时间数字转换等 https://github.com/dart-lang/intl
  intl: ^0.15.7
  # 图片浏览 https://pub.flutter-io.cn/packages/image_picker
  photo_view: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - images/ic_logo.png
  - images/ic_call.png
  - images/ic_call_sel.png
  - images/ic_check_report.png
  - images/ic_check_report_sel.png
  - images/ic_index.png
  - images/ic_index_sel.png
  - images/ic_report_history.png
  - images/ic_report_history_sel.png
  - images/ic_history_task.png
  - images/ic_history_dossier.png
  - images/ic_monitor_data.png
  - images/ic_warn_data.png
  - images/ic_laboratory_data.png
  - images/ic_product_data.png
  - images/ic_product_plan.png
  - images/ic_device_info.png
  - images/ic_filter.png
  - images/ic_problem.png
  - images/ic_produce.png
  - images/ic_patrol_task.png
  - images/ic_dossier_task.png
  - images/ic_test.png
  - images/ic_circle_check_blue.png
  - images/ic_circle_check_gray.png
  - images/ic_pend_test.png
  - images/ic_check_blue.png
  - images/ic_check_gray.png
  - images/ic_x_blue.png
  - images/ic_x_gray.png
  - images/ic_real_time_curves.png
  - images/ic_on_time_flag.png
  - images/ic_postpone_flag.png
  - images/ic_loading_pic.png
  - images/ic_star_blue.png
  - images/ic_star_gray.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
